name: Miri

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: miri

      - name: Run unit tests
        run: |
          cargo miri test
        env:
          MIRIFLAGS: -Zmiri-disable-isolation
          RUST_BACKTRACE: 1